# Generated by Django 3.2.9 on 2021-12-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250)),
                ('slug', models.CharField(blank=True, default='', max_length=250)),
                ('leave', models.CharField(blank=True, default='', max_length=250)),
                ('come', models.CharField(blank=True, default='', max_length=250)),
                ('status', models.CharField(blank=True, default='', max_length=250)),
            ],
        ),
    ]
